# Generated by Django 3.2 on 2021-06-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210627_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestionbox',
            name='category',
            field=models.CharField(choices=[('Suggestions', 'Suggestions'), ('Complaint', 'Complaint')], default='Suggestions', help_text='Please Select the nature of your suggestion', max_length=35),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='description',
            field=models.TextField(help_text='Share your Experience With us! We Would like to hear from you!'),
        ),
        migrations.AlterField(
            model_name='suggestionbox',
            name='event',
            field=models.ForeignKey(blank=True, help_text='if you are sharing something reguarding some event, please select that event here!', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.event'),
        ),
    ]
